# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=20)),
                ('gateway_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czo.Gateways')),
            ],
        ),
        migrations.CreateModel(
            name='Sensers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('node_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czo.Nodes')),
            ],
        ),
    ]
