# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0002_auto_20161127_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=40)),
                ('sensor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czo.Sensor')),
            ],
        ),
    ]
