# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0005_auto_20161204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.CharField(default=b'https://d3s5r33r268y59.cloudfront.net/97443/products/thumbs/2016-08-30T16:15:27.419Z-IMG-20160823-WA0018.jpg.855x570_q85_pad_rcrop.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.CharField(default=b'https://upload.wikimedia.org/wikipedia/commons/0/09/CCD_Image_sensor.jpg', max_length=400),
        ),
    ]
