# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0012_auto_20170118_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.FloatField(default=1.0),
        ),
    ]
