# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0014_auto_20170118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc',
            field=models.FloatField(blank=True, max_length=16),
        ),
    ]
