# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0017_auto_20170220_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-doc']},
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
