# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0018_auto_20170331_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True, max_length=196)),
                ('doc', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(help_text=b'rssi value')),
                ('vcell', models.FloatField(help_text=b'battery voltage')),
                ('soc', models.FloatField(help_text=b'state of charge')),
                ('lastUpdate', models.DateTimeField(default=datetime.datetime.now)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czo.Gateway')),
            ],
            options={
                'ordering': ['-lastUpdate'],
            },
        ),
        migrations.CreateModel(
            name='NodeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(help_text=b'rssi value')),
                ('battery', models.FloatField(help_text=b'battery voltage')),
                ('lastUpdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-lastUpdate'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='node',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='description',
        ),
        migrations.AddField(
            model_name='node',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='desc',
            field=models.TextField(blank=True, max_length=196),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='node',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='nodestats',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czo.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='gateway_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='czo.Gateway'),
            preserve_default=False,
        ),
    ]
