# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0019_auto_20170402_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='node_name',
        ),
        migrations.AlterModelOptions(
            name='nodestats',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='nodestats',
            old_name='lastUpdate',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='nodestats',
            name='data',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
