# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0020_auto_20170405_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewaystats',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='gatewaystats',
            old_name='lastUpdate',
            new_name='timestamp',
        ),
    ]
