# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0021_auto_20170405_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaystats',
            name='free_memory',
            field=models.IntegerField(default=30, help_text=b'Free memory'),
            preserve_default=False,
        ),
    ]
