# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czo', '0022_gatewaystats_free_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='desc',
            new_name='description',
        ),
    ]
