# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gateways',
            new_name='Gateway',
        ),
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
        migrations.RenameModel(
            old_name='Sensers',
            new_name='Sensor',
        ),
    ]
