# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0016_auto_20170201_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
